<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.glitch</groupId>
    <artifactId>glitch</artifactId>
    <version>1.0.0</version>
    <name>glitch</name>
    <description>glitch.paris</description>

    <properties>
        <javaVersion>25</javaVersion>
        <kotlinVersion>2.3.20</kotlinVersion>
        <junitVersion>${project.property("junitVersion").toString()}</junitVersion>
        <http4kVersion>6.43.0.0</http4kVersion>
        <mainClass>com.glitch.GlitchKt</mainClass>
        <skipMinify>false</skipMinify>
        <project.static>${project.basedir}/src/main/resources/static</project.static>
        <project.scripts>${project.basedir}/src/script</project.scripts>
    </properties>

    <dependencies>
        <dependency>
                <groupId>org.http4k</groupId>
                <artifactId>http4k-connect-storage-jdbc</artifactId>
                <version>${http4kVersion}</version>
        </dependency>
        <dependency>
                <groupId>org.http4k</groupId>
                <artifactId>http4k-core</artifactId>
                <version>${http4kVersion}</version>
        </dependency>
        <dependency>
                <groupId>org.http4k</groupId>
                <artifactId>http4k-format-jackson</artifactId>
                <version>${http4kVersion}</version>
        </dependency>
        <dependency>
                <groupId>org.http4k</groupId>
                <artifactId>http4k-format-kotlinx-serialization</artifactId>
                <version>${http4kVersion}</version>
        </dependency>
        <dependency>
                <groupId>org.http4k</groupId>
                <artifactId>http4k-server-jetty</artifactId>
                <version>${http4kVersion}</version>
        </dependency>
        <dependency>
                <groupId>org.http4k</groupId>
                <artifactId>http4k-template-thymeleaf</artifactId>
                <version>${http4kVersion}</version>
        </dependency>
        <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>9.7.0</version>
        </dependency>
        <dependency>
                <groupId>org.jetbrains.exposed</groupId>
                <artifactId>exposed-core</artifactId>
                <version>1.2.0</version>
        </dependency>
        <dependency>
                <groupId>org.jetbrains.exposed</groupId>
                <artifactId>exposed-jdbc</artifactId>
                <version>1.2.0</version>
        </dependency>
        <dependency>
                <groupId>org.jetbrains.exposed</groupId>
                <artifactId>exposed-dao</artifactId>
                <version>1.2.0</version>
        </dependency>

        <dependency>
                <groupId>org.http4k</groupId>
                <artifactId>http4k-testing-hamkrest</artifactId>
                <version>${http4kVersion}</version>
                <scope>test</scope>
        </dependency>
        <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>6.0.3</version>
                <scope>test</scope>
        </dependency>
        <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>6.0.3</version>
                <scope>test</scope>
        </dependency>
        <dependency>
                <groupId>org.junit.platform</groupId>
                <artifactId>junit-platform-launcher</artifactId>
                <version>6.0.3</version>
                <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
        <finalName>${project.artifactId}-${project.version}</finalName>
        <plugins>
            <plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.6.3</version>
				<executions>
					<execution>
						<id>css-minify</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<skip>${skipMinify}</skip>
							<useMavenLogger>true</useMavenLogger>
							<executable>${project.scripts}/minify_css.sh</executable>
							<arguments>
								<argument>${project.static}</argument>
							</arguments>
						</configuration>
					</execution>
					<execution>
						<id>js-minify</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<skip>${skipMinify}</skip>
							<useMavenLogger>true</useMavenLogger>
							<executable>${project.scripts}/minify_js.sh</executable>
							<arguments>
								<argument>${project.static}</argument>
							</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlinVersion}</version>

                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>

                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>

                <dependencies>
                    <dependency>
                        <groupId>org.http4k</groupId>
                        <artifactId>http4k-bom</artifactId>
                        <version>${http4kVersion}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-allopen</artifactId>
                        <version>${kotlinVersion}</version>
                    </dependency>
                </dependencies>

                <configuration>
                    <jvmTarget>${javaVersion}</jvmTarget>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.8.0</version>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <appendAssemblyId>false</appendAssemblyId>
                            <archive>
                                <manifest>
                                    <mainClass>${mainClass}</mainClass>
                                </manifest>
                            </archive>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
