server.port=8091

# System path will be used for storing images, docments, etc that may be added over time.
application.path.external=${GLITCH_PATH}
application.api_key="test"

spring.application.name=glitch
spring.web.resources.static-locations=classpath:/static,file:${application.path.external}/static

# Files downloadable through GET /documents/<filename> must exist on this list. 
# The files should be placed in ${application.path.external}/document/
documents.allowed={"versement_mobilites.pdf"}